name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  GEM_NAME: webgem

jobs:
  test:
    name: Test on GitHub-hosted Ruby
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ "2.7.8", "3.2.2" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake spec

  publish:
    name: Publish gem
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Echo context
        run: |
         echo "GITHUB_REF = $GITHUB_REF"
         echo "GITHUB_SHA = $GITHUB_SHA"
         echo "TAG = ${GITHUB_REF#refs/tags/}"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Build gem
        run: |
          # load versipn from code 
          version=$(ruby -e "require './lib/webgem/version'; puts Webgem::VERSION")
          tag=${GITHUB_REF#refs/tags/}

          echo "Gem version: $version"
          echo "Tag: $tag"
           i
           f [ "v$version" != "$tag" ]; then
          echo "ERROR: tag ($tag) does not match gem version (v$version)"
          exit 1
          fi

          bundle exec  racke build
          


      - name: Publish to RubyGems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
             version=$(ruby -e "require './lib/webgem/version'; puts Webgem::VERSION")
              gem_file="pkg/${GEM_NAME}-${version}.gem"
              echo "Publishing $gem_file"
               ls -lah pkg
